### ISSUE TITLE
A guide on how to install your dotfiles.

### ISSUE THREAD

**Issue by FirestormeDS** [CelticBoozer/dotfiles#213]
hello, am new to the "dotfiles" world and i know i just need to copy the things on .config directory to mine but theres other things you have, that i dont know how install and configure them like the .bin folder you got and etc... so if its possible to guide me through i will be thankful :).

**Comment by CelticBoozer** [comment]
Greetings, I apologize for the long reply.
Unfortunately at the moment my README file is not quite up to date and some things are not described or are outdated, I will try to update it today-tomorrow and let you know so you don't have any more questions. Thank you for your interest in my project.

**Comment by FirestormeDS** [comment]
thx

**Comment by CelticBoozer** [comment]
@FirestormeDS  Sry, 4 a long reply, think u can check it now
